#!/bin/bash

export QT_XCB_GL_INTEGRATION=none 

case $INSYNC_CMD in
    1)
        echo "---> 1" >>/tmp/insync.log
        INSYNC_CMD=2 $0 &
        insync start --no-daemon >>/tmp/insync.log 2>&1
        kill $(cat /tmp/insync.pid) 
    ;;
    2)
        echo "---> 2" >>/tmp/insync.log
        set -x
        insync version
        while ! [ -e "/tmp/insync$(id -u).sock" ] ; do
            sleep 1
        done
        sleep 1
        insync show
    ;;
    *)
        rm -f /tmp/insync.pid
        >/tmp/insync.log
        echo $$ >/tmp/insync.pid
        INSYNC_CMD=1 xvfb-cmd $0 &
        tail -f /tmp/insync.log
    ;;
esac

exit
